Admin.EndPoint/Controllers/LessonController.cs
using AcademyManagement.Application.DTOs.Lesson;
using AcademyManagement.Application.Services.Interfaces;
using AcademyManagement.Infrastructure.Http;
using Microsoft.AspNetCore.Mvc;

namespace Admin.EndPoint.Controllers
{
    public class LessonController : BaseController
    {
        #region Constructor

        private readonly ILessonService _lessonService;

        public LessonController(ILessonService lessonService)
        {
            _lessonService = lessonService;
        }

        #endregion

        #region Lessons

        [Route("Admin/Lessons")]
        public async Task<IActionResult> Lessons(FilterLessonDTO filter)
        {
            var lessons = await _lessonService.FilterLessons(filter);
            return View(lessons);
        }

        #endregion

        #region  Add Lesson

        [Route("Admin/AddLesson")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLesson(AddOrEditLessonDTO addLessonDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _lessonService.AddLesson(addLessonDTO);

                switch (res)
                {
                    case AddLessonResult.ExistLesson:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "نام درس وارد شده تکراری است", null);

                    case AddLessonResult.CantUploadFile:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "فایل انتخاب شده قابل بارگذاری نمی باشد", null);

                    case AddLessonResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "درس با موفقیت ثبت شد", null);


                }
            }
            return View(addLessonDTO);
        }

        #endregion

        #region  EDit Lesson

        [Route("Admin/EditLesson")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditLesson(AddOrEditLessonDTO editLessonDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _lessonService.EditLesson(editLessonDTO);

                switch (res)
                {
                    case EditLessonResult.ExistLesson:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "نام درس وارد شده تکراری است", null);

                    case EditLessonResult.NotFound:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "درسی با این مشخصات یافت نشد", null);

                    case EditLessonResult.CantUploadFile:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "فایل انتخاب شده قابل بارگذاری نمی باشد", null);

                    case EditLessonResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "درس با موفقیت ویرایش شد", null);


                }
            }
            return View(editLessonDTO);
        }

        #endregion

        #region Delete Lesson

        [Route("Admin/DeleteLesson/{lessonId}")]
        public async Task<IActionResult> DeleteLesson(int lessonId)
        {
            var res = await _lessonService.DeleteLesson(lessonId);

            switch (res)
            {
                case DeleteLessonResult.NotFound:
                    return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "درسی با این مشخصات یافت نشد", null);

                case DeleteLessonResult.Success:
                    return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "درس با موفقیت حذف شد", null);


            }
            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "عملیات با خطا مواجه شد", null);


        }

        #endregion

        #region Get Lessons Json

        [Route("Admin/GetLessonsJson")]
        public async Task<IActionResult> GetLessonsJson(string lessonName)
        {
            var lessons=await _lessonService.FilterLessonsByName(lessonName);
            return new JsonResult(lessons);
        }

        #endregion
    }
}

Admin.EndPoint/Controllers/RoleController.cs
using AcademyManagement.Application.DTOs.Role;
using AcademyManagement.Application.Services.Interfaces;
using AcademyManagement.Infrastructure.Http;
using Microsoft.AspNetCore.Mvc;

namespace Admin.EndPoint.Controllers
{
    public class RoleController : BaseController
    {
        #region  Constructor

        private readonly IRoleService _roleService;

        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }


        #endregion

        #region  Roles

        [Route("Admin/Roles")]
        public async Task<IActionResult> Roles()
        {
            var roles = await _roleService.GetAllRoles();
            return View(roles);
        }

        #endregion

        #region  Add Role

        [Route("Admin/AddRole")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(AddOrEditRoleDTO addOrEditRoleDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _roleService.AddRole(addOrEditRoleDTO);

                switch (res)
                {
                    case AddRoleResult.RoleNameIsDuplcate:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "نام نقش وارد شده تکراری است", null);

                    case AddRoleResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "نقش با موفقیت ثبت شد", null);


                }
            }
            return View(addOrEditRoleDTO);
        }

        #endregion

        #region  Edit Role

        [Route("Admin/EditRole")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRole(AddOrEditRoleDTO editRoleDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _roleService.EditRole(editRoleDTO);

                switch (res)
                {
                    case EditRoleResult.RoleNameIsDuplicate:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "نام نقش وارد شده تکراری است", null);

                    case EditRoleResult.NotFound:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Warning, "نقشی با این مشخصات یافت نشد",  null);


                    case EditRoleResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "نقش با موفقیت ویرایش شد", null);


                }
            }
            return View(editRoleDTO);
        }

        #endregion
    }
}

Admin.EndPoint/Controllers/TermController.cs
using System.Net.Http.Headers;
using AcademyManagement.Application.DTOs.Term;
using AcademyManagement.Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Admin.EndPoint.Controllers
{
    public class TermController:BaseController
    {
        #region Constructor

        private readonly ITermService _termService;

        public TermController(ITermService termService)
        {
            _termService = termService;
        }

        #endregion

        #region Terms

        [Route("Admin/Terms")]
        public async Task<IActionResult> Terms(FilterTermDTO filter)
        {
            var terms=await _termService.FilterTerms(filter);
            return View(terms);
        }

        #endregion

        #region Add Term

        [Route("Admin/AddTerm")]
        public IActionResult AddTerm()
        {
            return View();
        }

        [Route("Admin/AddTerm")]
        [HttpPost]
        public IActionResult AddTerm(AddTermDTO addTermDTO)
        {
            if (ModelState.IsValid)
            {

            }
            return View(addTermDTO);
        }

        #endregion
    }
}

Admin.EndPoint/Controllers/UserController.cs
using System.Runtime.Serialization.Json;
using System.Text.Json;
using AcademyManagement.Application.DTOs.User;
using AcademyManagement.Application.Services.Interfaces;
using AcademyManagement.Infrastructure.Http;
using Microsoft.AspNetCore.Mvc;

namespace Admin.EndPoint.Controllers
{
    public class UserController : BaseController
    {
        #region  Constructor

        private readonly IUserService _userService;
        private readonly IRoleService _roleService;

        public UserController(IUserService userService, IRoleService roleService)
        {
            _userService = userService;
            _roleService = roleService;
        }





        #endregion

        #region Users

        [Route("Admin/Users")]
        public async Task<IActionResult> Users(FilterUsersDTO filter)
        {
            filter.HowManyShowPageAfterAndBefore = 7;
            var users = await _userService.FilterUsers(filter);
            return View(users);
        }

        #endregion

        #region  Add User

        [Route("Admin/AddUser")]
        public async Task<IActionResult> AddUser()
        {

            #region Fill Role List

            ViewData["Roles"] = await _roleService.GetAllRoles();

            #endregion

            return View();
        }

        [Route("Admin/AddUser")]
        [HttpPost]
        public async Task<IActionResult> AddUser(AddUserDTO addUserDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _userService.AddUser(addUserDTO);

                switch (res)
                {
                    case AddUserResult.CantUploadAvatar:
                        TempData[Toast_ErrorMessage] = "تصویر انتخاب شده قابل بارگذاری نمی باشد";
                        break;

                    case AddUserResult.PhoneNumberIsExist:
                        TempData[Toast_ErrorMessage] = "شماره موبایل وارد شده قبلا ثبت شده است";
                        break;

                    case AddUserResult.EmailIsExist:
                        TempData[Toast_ErrorMessage] = " ایمیل وارد شده قبلا ثبت شده است";
                        break;

                    case AddUserResult.Success:
                        TempData[Toast_SuccessMessage] = "کاربر با موفقیت ثبت شد";
                        return RedirectToAction(nameof(Users));
                }
            }

            #region Fill Role List

            ViewData["Roles"] = await _roleService.GetAllRoles();

            #endregion


            return View(addUserDTO);
        }

        #endregion


        #region  Edit User

        [Route("Admin/EditUser/{userId}")]
        public async Task<IActionResult> EditUser(string userId)
        {
            var userDetails = await _userService.GetUserDetailsForEdit(userId);

            if (userDetails == null)
            {
                TempData[SweetAlert_ErrorMessage] = "کاربری با این مشخصصات یافت نشد";
                return RedirectToAction(nameof(Users));
            }

            #region Fill Role List

            ViewData["Roles"] = await _roleService.GetAllRoles();

            #endregion

            return View(userDetails);
        }

        [Route("Admin/EditUser/{userId?}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(EditUserDTO editUserDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _userService.EditUser(editUserDTO);

                switch (res)
                {
                    case EditUserResult.Success:
                        TempData[SweetAlert_SuccessMessage] = "ویرایش کاربر با موفقیت انجام شد";
                        return RedirectToAction(nameof(Users));

                    case EditUserResult.NotFoundUser:
                        TempData[Toast_WarningMessage] = "کاربری با این مشخصات یافت نشد";
                        break;

                    case EditUserResult.PhoneNumberIsExist:
                        TempData[Toast_WarningMessage] = "شماره موبایل وارد شده قبلا در سایت ثبت شده است";
                        break;

                    case EditUserResult.EmailIsExist:
                        TempData[Toast_WarningMessage] = "ایمیل وارد شده قبلا در سایت ثبت شده است";
                        break;

                    case EditUserResult.CantUploadAvatar:
                        TempData[Toast_ErrorMessage] = "تصویر انتخاب شده قابل بارگذاری نمی باشد";
                        break;
                }


            }

            #region Fill Role List

            ViewData["Roles"] = await _roleService.GetAllRoles();

            #endregion

            return View(editUserDTO);
        }

        #endregion


        #region  Delete User

        [Route("Admin/DeleteUser/{userId}")]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            if (ModelState.IsValid)
            {
                var res = await _userService.DeleteUser(userId);

                switch (res)
                {
                    case DeleteUserResult.NotFound:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Warning, "کاربری با این مشخصات یافت نشد", null);


                    case DeleteUserResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "کاربر با موفقیت حذف شد", null);


                }
            }
            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "عملیات مورد نظر با خطا مواجه شد", null);

        }

        #endregion

        #region Get Teachers Json

        [Route("Admin/GetTeachersJson")]
        public async Task<string> GetTeachersJson([FromServices]ITeacherService teacherService)
        {
            var teachers=await teacherService.GetTeachersForTerm();
            return JsonSerializer.Serialize(teachers);
        }

        #endregion


    }
}

Admin.EndPoint/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<!-- Head -->
<head>
    <meta charset="utf-8" />
    <title>مدیریت آموزشگاه | @ViewData["Title"]</title>
    <meta name='robots' content='noindex, nofollow' />
    <meta name="description" content="Dashboard" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <partial name="_AdminStyles" />
    @RenderSection("Styles",false)
</head>
<!-- /Head -->
<!-- Body -->
<body>
    <!-- Loading Container -->
    <div class="loading-container">
        <div class="loader"></div>
    </div>
    <!--  /Loading Container -->
    <!-- Navbar -->
    @await Component.InvokeAsync("AdminHeader")
    <!-- /Navbar -->
    <!-- Main Container -->
    <div class="main-container container-fluid">
        <!-- Page Container -->
        <div class="page-container">
            <partial name="_AdminSidebar" />

            <!-- Page Content -->
            <div class="page-content">
                <!-- Page Breadcrumb -->
                <div class="page-breadcrumbs">
                    <ul class="breadcrumb">
                        <li>
                            <i class="fa fa-home"></i>
                            <a asp-area="Admin" asp-controller="Home" asp-action="Index">خانه</a>
                        </li>
                        @RenderSection("BreadCrumb",false)
                        <li class="active">@ViewData["Title"]</li>
                    </ul>
                </div>
                <!-- /Page Breadcrumb -->
                <!-- Page Header -->
                <div class="page-header position-relative">
                    <div class="header-title">
                        <h1>
                            @ViewData["Title"]
                        </h1>
                    </div>
                    <!--Header Buttons-->
                    <div class="header-buttons">
                        <a class="sidebar-toggler" href="#">
                            <i class="fa fa-arrows-h"></i>
                        </a>
                        <a class="refresh" id="refresh-toggler" href="">
                            <i class="glyphicon glyphicon-refresh"></i>
                        </a>
                        <a class="fullscreen" id="fullscreen-toggler" href="#">
                            <i class="glyphicon glyphicon-fullscreen"></i>
                        </a>
                    </div>
                    <!--Header Buttons End-->
                </div>
                <!-- /Page Header -->
                <!-- Page Body -->
                <div class="page-body">
                    @RenderBody()

                </div>

            </div>

        </div>
        <!-- /Page Container -->
        <!-- Main Container -->

    </div>

    <partial name="_AdminScripts" />
    <partial name="_SiteMessages" />
    @RenderSection("Scripts",false)

</body>
</html>

Admin.EndPoint/Views/Shared/_AdminPagingPartial.cshtml
@model AcademyManagement.Application.DTOs.Paging.BasePaging

<ul class="pagination">
    @if (Model.StartPage < Model.PageId)
    {
        <li class="cursor-pointer"><a onclick="FillPageId(@(Model.PageId - 1))">«</a></li>
    }

    @for (int i = Model.StartPage; i <= Model.EndPage; i++)
    {
        <li class="@(Model.PageId == i ? "active":"") cursor-pointer"><a onclick="FillPageId(@i)">@i<span class="sr-only">(current)</span></a></li>
    }

    @if (Model.EndPage > Model.PageId)
    {
        <li class="cursor-pointer"><a onclick="FillPageId(@(Model.PageId + 1))">»</a></li>
    }
</ul>

Admin.EndPoint/Views/Shared/_AdminScripts.cshtml
<script src="/js/jquery.min.js" asp-append-version="true"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/skins.min.js"></script>
<script src="/js/slimscroll/jquery.slimscroll.min.js" asp-append-version="true"></script>
<script src="/js/beyond.min.js" asp-append-version="true"></script>
<script src="/js/notifications.js" asp-append-version="true"></script>
<script src="/js/sweetalert.min.js"></script>
<script src="/js/ShowNotificationMessage.js"></script>
<script src="/js/custome.js" asp-append-version="true"></script>

Admin.EndPoint/Views/Shared/_AdminSidebar.cshtml
@{
    var requestedPath = Context.Request.Path;
}

<!-- Page Sidebar -->
<div class="page-sidebar" id="sidebar">

    <!-- Sidebar Menu -->
    <ul class="nav sidebar-menu">
        <!--Dashboard-->
        <li class="@(requestedPath=="/Admin/Dashboard"?"active":"")">
            <a asp-controller="Home" asp-action="Dashboard">
                <i class="menu-icon glyphicon glyphicon-home"></i>
                <span class="menu-text"> داشبورد </span>
            </a>
        </li>

        <li class="@(requestedPath=="/Admin/Users"?"active":"")">
            <a asp-controller="User" asp-action="Users">
                <i class="menu-icon glyphicon glyphicon-user"></i>
                <span class="menu-text">کاربران</span>
            </a>
        </li>

        <li class="@(requestedPath=="/Admin/Roles"?"active":"")">
            <a asp-controller="Role" asp-action="Roles">
                <i class="menu-icon glyphicon glyphicon-lock"></i>
                <span class="menu-text">مدیرت نقش ها</span>
            </a>
        </li>

        <li class="@(requestedPath=="/Admin/PreRegisterations"?"active":"")">
            <a asp-controller="PreRegisteration" asp-action="PreRegisterations">
                <i class="menu-icon glyphicon glyphicon-bookmark"></i>
                <span class="menu-text">پیش ثبت نامی ها</span>
            </a>
        </li>
        <li class="@(requestedPath=="/Admin/Lessons"?"active":"")">
            <a asp-controller="Lesson" asp-action="Lessons">
                <i class="menu-icon glyphicon glyphicon-book"></i>
                <span class="menu-text">درس ها</span>
            </a>
        </li>
          <li class="@(requestedPath=="/Admin/Terms"?"active":"")">
            <a asp-controller="Term" asp-action="Terms">
                <i class="menu-icon fa fa-university"></i>
                <span class="menu-text">ترم ها</span>
            </a>
        </li>

    </ul>
    <!-- /Sidebar Menu -->
</div>
<!-- /Page Sidebar -->

Admin.EndPoint/Views/Shared/_AdminStyles.cshtml
<link rel="shortcut icon" href="/img/favicon.png" type="image/x-icon">
<link rel="stylesheet" href="/css/main.min.css" asp-append-version="true"/>
<link href="/css/beyond-rtl.min.css" rel="stylesheet" asp-append-version="true"/>
<link href="/css/custome.css" rel="stylesheet" asp-append-version="true"/>

Admin.EndPoint/Views/Shared/_SiteMessages.cshtml
@if (
TempData["ToastSuccessMessage"] != null ||
TempData["ToastErrorMessage"] != null ||
TempData["ToastWarningMessage"] != null ||
TempData["ToastInfoMessage"] != null ||
TempData["SweetAlertSuccessMessage"] != null ||
TempData["SweetAlertWarningMessage"] != null ||
TempData["SweetAlertErrorMessage"] != null ||
TempData["SweetAlertInfoMessage"] != null 
)
{
    if (TempData["ToastSuccessMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowToastMessageNotification('پیغام موفقیت', '@TempData["ToastSuccessMessage"]', 'success');
            });
        </script>
    }

    if (TempData["ToastErrorMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowToastMessageNotification('پیغام خطا', '@TempData["ToastErrorMessage"]', 'error');
            });
        </script>
    }

    if (TempData["ToastWarningMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowToastMessageNotification('پیغام اخطار', '@TempData["ToastWarningMessage"]', 'warning');
            });
        </script>
    }

    if (TempData["ToastInfoMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowToastMessageNotification('پیغام اطلاعیه', '@TempData["ToastInfoMessage"]', 'info');
            });
        </script>
    }

    if(TempData["SweetAlertSuccessMessage"]!=null)
    {
            <script>
            $(document).ready(function () {
                ShowSweetAlertNotification('پیغام موفقیت', '@TempData["SweetAlertSuccessMessage"]', 'success')
            });
        </script>
    }

    if(TempData["SweetAlertWarningMessage"]!=null)
    {
            <script>
            $(document).ready(function () {
                ShowSweetAlertNotification('پیغام اخطار', '@TempData["SweetAlertWarningMessage"]', 'warning')
            });
        </script>
    }

    if(TempData["SweetAlertErrorMessage"]!=null)
    {
            <script>
            $(document).ready(function () {
                ShowSweetAlertNotification('پیغام خطا', '@TempData["SweetAlertErrorMessage"]', 'error')
            });
        </script>
    }

    if(TempData["SweetAlertInfoMessage"]!=null)
    {
            <script>
            $(document).ready(function () {
                ShowSweetAlertNotification('پیغام اطلاعیه', '@TempData["SweetAlertInfoMessage"]', 'info')
            });
        </script>
    }
}