Admin.EndPoint/Controllers/LessonController.cs
using AcademyManagement.Application.DTOs.Lesson;
using AcademyManagement.Application.Services.Interfaces;
using AcademyManagement.Infrastructure.Http;
using Microsoft.AspNetCore.Mvc;

namespace Admin.EndPoint.Controllers
{
    public class LessonController : BaseController
    {
        #region Constructor

        private readonly ILessonService _lessonService;

        public LessonController(ILessonService lessonService)
        {
            _lessonService = lessonService;
        }

        #endregion

        #region Lessons

        [Route("Admin/Lessons")]
        public async Task<IActionResult> Lessons(FilterLessonDTO filter)
        {
            var lessons = await _lessonService.FilterLessons(filter);
            return View(lessons);
        }

        #endregion

        #region  Add Lesson

        [Route("Admin/AddLesson")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLesson(AddOrEditLessonDTO addLessonDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _lessonService.AddLesson(addLessonDTO);

                switch (res)
                {
                    case AddLessonResult.ExistLesson:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "نام درس وارد شده تکراری است", null);

                    case AddLessonResult.CantUploadFile:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "فایل انتخاب شده قابل بارگذاری نمی باشد", null);

                    case AddLessonResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "درس با موفقیت ثبت شد", null);


                }
            }
            return View(addLessonDTO);
        }

        #endregion

        #region  EDit Lesson

        [Route("Admin/EditLesson")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditLesson(AddOrEditLessonDTO editLessonDTO)
        {
            if (ModelState.IsValid)
            {
                var res = await _lessonService.EditLesson(editLessonDTO);

                switch (res)
                {
                    case EditLessonResult.ExistLesson:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "نام درس وارد شده تکراری است", null);

                    case EditLessonResult.NotFound:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "درسی با این مشخصات یافت نشد", null);

                    case EditLessonResult.CantUploadFile:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "فایل انتخاب شده قابل بارگذاری نمی باشد", null);

                    case EditLessonResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "درس با موفقیت ویرایش شد", null);


                }
            }
            return View(editLessonDTO);
        }

        #endregion

        #region Delete Lesson

        [Route("Admin/DeleteLesson/{lessonId}")]
        public async Task<IActionResult> DeleteLesson(int lessonId)
        {
            var res = await _lessonService.DeleteLesson(lessonId);

            switch (res)
            {
                case DeleteLessonResult.NotFound:
                    return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "درسی با این مشخصات یافت نشد", null);

                case DeleteLessonResult.Success:
                    return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "درس با موفقیت حذف شد", null);


            }
            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "عملیات با خطا مواجه شد", null);


        }

        #endregion

        #region Get Lessons Json

        [Route("Admin/GetLessonsJson")]
        public async Task<IActionResult> GetLessonsJson(string lessonName)
        {
            var lessons=await _lessonService.FilterLessonsByName(lessonName);
            return new JsonResult(lessons);
        }

        #endregion
    }
}

Admin.EndPoint/Controllers/PreRegisterationController.cs
using AcademyManagement.Application.DTOs.PreRegisteration;
using AcademyManagement.Application.Services.Interfaces;
using AcademyManagement.Infrastructure.Http;
using Microsoft.AspNetCore.Mvc;
using AcademyManagement.Application.DTOs.Account;

namespace Admin.EndPoint.Controllers
{
    public class PreRegisterationController : BaseController
    {
        #region Constructor

        private readonly IPreRegisterationService _preRegisterationService;

        public PreRegisterationController(IPreRegisterationService preRegisterationService)
        {
            _preRegisterationService = preRegisterationService;
        }

        #endregion

        #region  PreRegisterations

        [Route("Admin/PreRegisterations")]
        public async Task<IActionResult> PreRegisterations(FilterPreRegisterationDTO filter)
        {
            filter.HowManyShowPageAfterAndBefore = 7;
            var preRegisterations = await _preRegisterationService.FilterPreRegisteration(filter);

            return View(preRegisterations);
        }

        #endregion

        #region PreRegisteratin Details

        [Route("Admin/PreRegisteratinDetails/{preRegisterationId}")]
        public async Task<IActionResult> PreRegisteratinDetails(int preRegisterationId)
        {
            var preRegisteration = await _preRegisterationService.GetPreRegisteratinDetails(preRegisterationId);
            if (preRegisteration == null)
            {
                TempData[Toast_ErrorMessage] = "اطلاعاتی یافت نشد";
                return RedirectToAction(nameof(PreRegisterations));
            }
            return View(preRegisteration);

        }

        #endregion

        #region  Delete PreRegisteration

        [Route("Admin/DeletePreRegisteratin/{preRegisterationId}")]
        public async Task<IActionResult> DeletePreRegisteraton(int preRegisterationId)
        {
      
                var res = await _preRegisterationService.DeletePreRegisteration(preRegisterationId);

                switch (res)
                {
                    case DeletePreRegisterationResult.NotFound:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Warning, "پیش ثبت نامی با این مشخصات یافت نشد", null);


                    case DeletePreRegisterationResult.Success:
                        return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "پیش ثبت نامی با موفقیت حذف شد", null);


                }
            
            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Error, "عملیات مورد نظر با خطا مواجه شد", null);
        }


        #endregion

    }


}

Admin.EndPoint/Views/Lesson/Lessons.cshtml
@using AcademyManagement.Application.DTOs.Lesson
@using AcademyManagement.Application.Utils
@model FilterLessonDTO

@{
    ViewData["Title"] = "درس ها";
}

<div class="container margin-bottom-10">
    <a data-toggle="modal" data-target="#addLesson" class="btn btn-success">افزودن درس</a>
</div>
<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 ">
    <div class="well with-header">
        <div class="header bordered-sky">
            فیلتر
        </div>
        <form id="filter-form" asp-controller="PreRegisteration" asp-action="PreRegisterations" method="get">
            <input type="hidden" asp-for="PageId" />
            <div class="form-group">
                <label>نام درس</label>
                <input asp-for="LessonName" class="form-control">
            </div>
            <div class="form-group">
                <label>تعداد فصل</label>
                <input asp-for="SeasonCount" class="form-control">
            </div>
            <hr />
            <h4>مرتب سازی</h4>
            <div class="control-group">
                @foreach (var item in Html.GetEnumSelectList<FilterLessonOrder>())
                {
                    <div class="radio">
                        <label>
                            <input type="radio" class="colored-blue" value="@item.Value" name="@nameof(Model.OrderBy)"
                            @(Convert.ToInt32(item.Value) == Convert.ToInt32(Model.OrderBy) ? "checked" : "")>
                            <span class="text">@item.Text</span>
                        </label>
                    </div>
                }
            </div>
            <button type="submit" class="btn btn-success btn-block">فیلتر</button>
        </form>
    </div>
</div>

<div class="col-lg-8 col-md-8 col-sm-12 col-12 col-xs-12">
    <div class="well with-header with-footer">
        <div class="header bordered-sky">
            @ViewData["Title"]
        </div>
        @if (Model.Lessons != null && Model.Lessons.Any())
        {
            <div class="table-scrollable">

                <table class="table table-bordered table-hover text-center">
                    <thead>
                        <tr>
                            <th>
                                شناسه
                            </th>
                            <th>
                                نام درس
                            </th>
                            <th>
                                 تعداد فصل
                            </th>
                            <th>
                                  لینک دانلود فایل درس
                            </th>
                            <th>
                                دستورات
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var lesson in Model.Lessons)
                        {
                            <tr id="ajax-url-item-@lesson.Id">
                                <td>
                                    @lesson.Id
                                </td>
                                <td>
                                    @lesson.Name
                                </td>
                                <td>
                                    @lesson.Season_Count
                                </td>
                                <td>
                                    <a href="@(PathExtension.PdfLesson+lesson.Lesson_File)" class="btn btn-success">دانلود</a>
                                </td>
                                <td>
                                    <a data-toggle="modal" data-target="#editLesson-@lesson.Id"
                                        class="btn btn-warning btn-xs">ویرایش</a>
                                    <a asp-controller="Lesson" asp-action="DeleteLesson" asp-route-lessonId="@lesson.Id"
                                        ajax-url-button="@lesson.Id" class="btn btn-danger btn-xs">حذف</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>


        }
        else
        {
            <Alert type="warning" message="هیچ اطلاعاتی یافت نشد"></Alert>
        }
        <div class="footer">
            <partial name="_AdminPagingPartial" model="@Model.GetCurrentPaging()" />
        </div>
    </div>
</div>



<!-- start Add Lesson Modal -->

<div class="modal fade" id="addLesson" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">افزودن درس</h5>
                <button type="button" class="close margin-top-minus-21" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-group">

                    <form asp-controller="Lesson" asp-action="AddLesson" method="post" asp-antiforgery="true" enctype="multipart/form-data"
                        data-method="post" data-ajax="true" data-ajax-success="OnSuccessAddOrEditItem">
                        <partial name="_AddLesson" model="@(new AddOrEditLessonDTO{})" />
                        <div class="custome-modal-footer">
                            <button type="submit" class="btn btn-success pull-right">ثبت</button>
                            <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">بستن</button>
                        </div>
                    </form>

                </div>

            </div>

        </div>
    </div>
</div>
<!-- end Add Lesson Modal -->

@if(Model.Lessons!=null && Model.Lessons.Any())
{
    @foreach (var lesson in Model.Lessons)
    {
        <div class="modal fade" id="editLesson-@lesson.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ویرایش درس</h5>
                <button type="button" class="close margin-top-minus-21" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-group">

                    <form asp-controller="Lesson" asp-action="EditLesson" method="post" asp-antiforgery="true" enctype="multipart/form-data"
                        data-method="post" data-ajax="true" data-ajax-success="OnSuccessAddOrEditItem">
                        <partial name="_EditLesson" model="@(new AddOrEditLessonDTO{Id=lesson.Id,Name=lesson.Name,Season_Count=lesson.Season_Count})" />
                        <div class="custome-modal-footer">
                            <button type="submit" class="btn btn-success pull-right">ثبت</button>
                            <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">بستن</button>
                        </div>
                    </form>

                </div>

            </div>

        </div>
    </div>
</div>
    }
}

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Admin.EndPoint/Views/Lesson/_AddLesson.cshtml
@using AcademyManagement.Application.DTOs.Lesson
@model AddOrEditLessonDTO


<label>نام درس</label>
<input asp-for="Name" class="form-control" placeholder="لطفا نام درس را وارد کنید">
<span asp-validation-for="Name" class="text-danger"></span>

<label>تعداد فصل</label>
<input asp-for="Season_Count" class="form-control" placeholder="لطفا تعداد فصل درس را وارد کنید">
<span asp-validation-for="Season_Count" class="text-danger"></span>

<label>فایل درس</label>
<input asp-for="PdfFile" type="file" class="form-control">

Admin.EndPoint/Views/Lesson/_EditLesson.cshtml
@using AcademyManagement.Application.DTOs.Lesson
@model AddOrEditLessonDTO

<input type="hidden" asp-for="Id" />

<label>نام درس</label>
<input asp-for="Name" class="form-control" placeholder="لطفا نام درس را وارد کنید">
<span asp-validation-for="Name" class="text-danger"></span>

<label>تعداد فصل</label>
<input asp-for="Season_Count" class="form-control" placeholder="لطفا تعداد فصل درس را وارد کنید">
<span asp-validation-for="Season_Count" class="text-danger"></span>

<label>فایل درس</label>
<input asp-for="PdfFile" type="file" class="form-control">